### PR TITLE
Remove note about pah-fm's develop branch

### PR DESCRIPTION
**Pull request by arturtamborski**
It's not relevant anymore, we switched to master branch some time ago.

### CODE REVIEW

**Comment by OtisRed** [comment]
Given that @arturtamborski says it's irrelevant I'm closing it

**Comment by magul** [comment]
what is not relevant anymore? should it be merged because what it changes is unrelevant? @arturtamborski ?

**Comment by arturtamborski** [comment]
Uh, that's a bad choice of words from my side.

The note about pah's develop branch is irrelevant (see diff), which means that we can remove it (this PR). But the change itself is valid & needed to not cause confusion on meetings.

**Comment by magul** [comment]
we can remove that mention and merge that pull request or remove that pull request? that's confusing...

**Review by OtisRed — APPROVED** [review]

**Comment by OtisRed** [comment]
No harm no faul :)

**Comment by magul** [comment]
no damage, no fun!

**Comment by arturtamborski** [comment]
> we can remove that mention and merge that pull request or remove that pull request? that's confusing...

uhhh... yeah, it is! Please merge it :)

**Pull request merged**
